meta_product_name: "Complimenu"
meta_title: "Complimenu - a menu that compliments you"
meta_description: "Use Complimenu on your restaurant to have clients see a dynamic menu, order directly from the app, and even pay or ask for the check! They can also leave reviews for the dishes."
meta_image: "cover.png"
